[package]
name = "server"
version = "0.1.0"
authors = ["Alon Gal <alongalky@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rand = "0.6.0"

[dependencies.rusqlite]
version = "0.16.0"
features = ["bundled"]